#!/usr/bin/env python3
import sys
import bibtexparser

def loadBibtex(filename):
    print(f'Load {filename} bibtex database')
    with open(filename, encoding="utf-8") as bibtex_file:
        bib_database = bibtexparser.load(bibtex_file)
    return bib_database

def saveBibtex(filename, bib_database):
    print(f'Save {filename} bibtex database')
    with open(filename, "w", encoding="utf-8") as bibtex_file:
        bibtexparser.dump(bib_database, bibtex_file)
    
# --------------------------------------------------------    
# Start of the main program
# --------------------------------------------------------    
print ("cleanBibtex")
print ("(c) by Olivier Pantalé 2024-2025")
print ("")

remove = []

if (len(sys.argv) > 1):
    filename = sys.argv[1]
    bib_database = loadBibtex(filename)
    print(f'Database contains {len(bib_database.entries)} entries')
    for i in range(2,len(sys.argv)):
        remove.append(sys.argv[i])
    print(f'Removing fields {remove}')
    for entry in bib_database.entries:
        for p in remove:
            entry.pop(p, None)
    saveBibtex(filename, bib_database)
else:
    print ("Usage is the following:")
    print ("    cleanBibtex bibTexfile [options]")
