#!/usr/bin/env python3
import sys
#import glob
import os
from subprocess import PIPE, Popen

mandatoryArgs = 0

# --------------------------------------------------------    
# Start of the main program
# --------------------------------------------------------   
print ("killJupyter")
print ("(c) by Olivier Pantalé 2021")
    
if ('--help' in sys.argv):
    print ("Usage is the following:")
    print ("    killJupyter [options]")
    print ("Options:")
    print ("    --help              this help")
    exit(0)

print('Searching for jupyter notebook kernels')
p = Popen("/softwares/Python/bin/jupyter notebook list", shell=True, stdout=PIPE, stderr=PIPE)
stdout, stderr = p.communicate()
ret = stdout.decode().split('\n')
k = 0
for l in ret:
    if ('http://localhost' in l):
        port = l.split('http://localhost:')[1].split('/?token=')[0]
        print('Stop server on port :',port)
        os.system('/softwares/Python/bin/jupyter notebook stop ' + port + '> /dev/null')
        k+=1
if (k == 0): print('No jupyter notebook kernel found')

k = 0
print('Searching for jupyter lab kernels')
p = Popen("/softwares/Python/bin/jupyter lab list", shell=True, stdout=PIPE, stderr=PIPE)
stdout, stderr = p.communicate()
ret = stdout.decode().split('\n')
for l in ret:
    if ('http://localhost' in l):
        port = l.split('http://localhost:')[1].split('/?token=')[0]
        print('Stop server on port :',port)
        os.system('/softwares/Python/bin/jupyter lab stop ' + port + '> /dev/null')
        k+=1
if (k == 0): print('No jupyter lab kernel found')
                      
