#!/usr/bin/env python3
import sys
import glob
from send2trash import send2trash

def getFileToDelete(src, tag):
    lst = []
    allFiles = glob.glob(src)
    keepFiles = glob.glob(tag)
    for f in allFiles:
        if not f in keepFiles:
            lst.append(f)
    return lst

def sendToTrash(lst):
    for f in lst:
        send2trash(f)
                    
# --------------------------------------------------------    
# Start of the main program
# --------------------------------------------------------    
print ("removeExcept")
print ("(c) by Olivier Pantalé 2023-2025")
print ("")
if (len(sys.argv) > 2):
    
    src = sys.argv[1]
    tag = sys.argv[2]
    print(f"Remove all files but {tag} files")

    todel = getFileToDelete(src, tag)
    print(todel)
    
    sendToTrash(todel)
                
else:
    print ("Usage is the following:")
    print ("    removeExcept files [pattern]")
    print ("    files     files to look for")
    print ("    pattern   pattern of the files to keep")
    print ("Options:")
